on:
  push:
    branches:
      - '*'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install    # Optional: Install dependencies if needed
      - run: npm test       # Run tests