on:
  push:
    branches:
      - '*'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  run_tests:
    runson: ubuntu-latest
    steps:
      - run: npm test